#!/usr/bin/env node

var path     = require('path');
var fs       = require('fs.extra');
var color    = require('colors');
var request  = require('request');
var uploader = require('file-uploader');
var utils    = require('./utils.js');
var pack     = require('./package.json');

var args   = process.argv.slice(2);
var config = utils.getConfig();

if (!args.length || args[0] === '--help' || args[0] === 'help') {
  console.log('Sona, version ' + pack.version + '\n');
  console.log('   init [dir]\t\tIntializes a new Sona project');
  console.log('   config\t\tView saved settings');
  console.log('   publish [name]\tUpload extension to Sona server - defaults extension name to name of directory');
  console.log('   login\t\tAuthenticate yourself as the author of published extensions');
  console.log('   logout\t\tLog off of this device');
  return;
} else if (args[0] === '--autocomplete') {
  fs.appendFile(path.join(utils.getHome(), '.profile'), 'source ' + utils.lodir('autocomplete.sh'), function (err) {
    console.log('Autocomplete enabled!'.green);
  });
  return;
}

// Load in available commands
var cmds = [];
fs.readdirSync(utils.lodir('commands')).forEach(function(file) {
  cmds.push(file.slice(0, -3));
});

if (cmds.indexOf(args[0]) !== -1) {
  var filename = utils.lodir('commands', args[0]);
  var cmd = require(filename);

  cmd.run(args);
} else {
  utils.error('sona: \'' + args[0] + '\' is not a sona command. See \'sona --help\'');
}
